# Numpy

### NumPy is an essential and powerful library in Python for numerical computing. Its importance stems from the numerous benefits it offers for working with arrays and performing mathematical operations efficiently. Here are some key reasons why NumPy is so important:

### NumPy seamlessly integrates with other scientific computing and data manipulation libraries in Python, such as SciPy (Scientific Python library), Pandas (Data Analysis library), and Matplotlib (Plotting library). These libraries often use NumPy arrays as their fundamental data structure.

# Step 1: Import NumPy

In [2]:
import numpy as np

# Step 2: Creating NumPy Arrays
## You can create NumPy arrays in various ways. Some common methods include:

### a) From Python Lists:

In [3]:
# 1D array
arr1d = np.array([1, 2, 3, 4, 5])

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr1d)
print(arr2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### b) Using NumPy Functions:

In [4]:
# Create a 1D array of zeros
zeros_arr = np.zeros(5)

# Create a 2D array of ones with a shape of (3, 4)
ones_arr = np.ones((3, 4))

# Create a 1D array with values in a specified range (start, stop, step)
range_arr = np.arange(0, 10, 2)

# Create a 1D array of equally spaced values between start and stop
linspace_arr = np.linspace(0, 1, 5)

print(zeros_arr)
print(ones_arr)
print(range_arr)
print(linspace_arr)

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


# Step 3: Array Attributes
### NumPy arrays have several attributes that provide information about the array:

In [5]:
arr = np.array([1, 2, 3, 4, 5])

print("Shape of the array:", arr.shape)  # Output: (5,) - 1D array with 5 elements
print("Number of dimensions:", arr.ndim)  # Output: 1 - 1D array
print("Size of the array:", arr.size)     # Output: 5 - 5 elements in the array
print("Data type of the array:", arr.dtype)  # Output: int64 - the data type of the array

Shape of the array: (5,)
Number of dimensions: 1
Size of the array: 5
Data type of the array: int32


## Shape of the array: 
### The shape of a NumPy array is a tuple representing the number of elements along each dimension of the array. In this case, the shape (5,) indicates that the array is a 1-dimensional array (1D) with 5 elements. The comma after the 5 indicates that the tuple contains only one element, which corresponds to the number of elements in the first (and only) dimension of the array. The shape is specified as (5,), where 5 denotes the length of the array along the first dimension.

## Size of the array: 
### The size of a NumPy array refers to the total number of elements present in the array. It represents the count of all the individual elements contained within the array, regardless of the number of dimensions. In this case, the size is 5, which means the array contains a total of 5 elements.

##### int32" means that the data type of the elements in the array is 32-bit signed integer. In the example "Data type of the array: int32," the elements in the array are integers, and the specific data type used to represent those integers is a 32-bit signed integer. The 'int32' data type means that each integer element in the array occupies 32 bits (4 bytes) of memory and can represent integer values in the range from -2,147,483,648 to 2,147,483,647.

In [6]:
arr = np.array([[1, 2, 3, 4, 5], [1, 2, 4, 5, 6]])

print("The array", arr)
print("Shape of the array:", arr.shape)  # Output: (5,) - 1D array with 5 elements
print("Number of dimensions:", arr.ndim)  # Output: 1 - 1D array
print("Size of the array:", arr.size)     # Output: 5 - 5 elements in the array
print("Data type of the array:", arr.dtype)  # Output: int64 - the data type of the array

The array [[1 2 3 4 5]
 [1 2 4 5 6]]
Shape of the array: (2, 5)
Number of dimensions: 2
Size of the array: 10
Data type of the array: int32


# Step 4: Array Indexing and Slicing
### NumPy arrays support indexing and slicing similar to Python lists:

In [7]:
arr = np.array([10, 20, 30, 40, 50])

print("Element at index 2:", arr[2])      # Output: 30
print("Elements from index 1 to 3:", arr[1:4])  # Output: [20, 30, 40]
print("Every second element:", arr[::2])   # Output: [10, 30, 50]

Element at index 2: 30
Elements from index 1 to 3: [20 30 40]
Every second element: [10 30 50]


### For 2D arrays, you can access elements using two indices:

In [4]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Print the array\n", arr2d)
print("Element at row 2, column 3:", arr2d[1, 2])  # Output: 6
print("First two rows:", arr2d[:2, :])            # Output: [[1 2 3] [4 5 6]]

# Looping through 2D arrays
    
# Initialize an empty 2D array of the same shape as array1
array2 = np.empty_like(arr2d)

# Using nested for loops to copy elements from array1 to array2
for i in range(len(arr2d)):
    for j in range(len(arr2d[i])):
        array2[i][j] = arr2d[i][j]

# Print array2
print("Array2:")
print(array2)

Print the array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 2, column 3: 6
First two rows: [[1 2 3]
 [4 5 6]]
Array2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Step 5: Array Operations
### NumPy arrays support various mathematical operations, and these operations are element-wise:

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
result_add = a + b

# Element-wise multiplication
result_mul = a * b

# Matrix multiplication (dot product)
result_dot = np.dot(a, b)
# a[0] * b[0] = 1 * 4 = 4
# a[1] * b[1] = 2 * 5 = 10
# a[2] * b[2] = 3 * 6 = 18
Sum = 4 + 10 + 18 = 32

print("Addition:", result_add)  # Output: [5 7 9]
print("Multiplication:", result_mul)  # Output: [4 10 18]
print("Dot Product:", result_dot)  # Output: 32

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot Product: 32


# Step 6: Reshaping Arrays
### You can reshape arrays to give them a new shape:

In [12]:
arr = np.arange(9)
reshaped_arr = arr.reshape((3, 3))

print("Original array:", arr)
print("Reshaped array:")
print(reshaped_arr)

Original array: [0 1 2 3 4 5 6 7 8]
Reshaped array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
